### ISSUE TITLE
Please refer and get Watcher TV working again

### ISSUE THREAD

**Issue by bachthuantieu** [janjanmedinaaa/lyrify#1]
Hello [janjanmedinaaa](https://github.com/janjanmedinaaa), I have been using your [Watcher TV](https://github.com/janjanmedinaaa/watcher-tv) app for a while, the app is very good to use
 and unfortunately it no longer works. Now I just found an app that uses **Loklok** api but still works, hope you can refer and get **Watcher TV** working again 💪

Link Repositorie: [https://github.com/hexated/cloudstream-extensions-hexated/blob/master/Loklok/src/main/kotlin/com/hexated/Loklok.kt](https://github.com/hexated/cloudstream-extensions-hexated/blob/master/Loklok/src/main/kotlin/com/hexated/Loklok.kt)

Image the app still works fine with Loklok api:

![image](https://github.com/janjanmedinaaa/lyrify/assets/92453077/58a54e27-91b7-4a57-8683-b5a51964bba3)

**Comment by janjanmedinaaa** [comment]
Hi, thanks for the support! I'll look into the repository you referred to and try to implement it on Watcher TV. It would probably take a couple of days since I can't work on it right now, but I have unarchived the repository (probably shouldn't have archived it in the first place, my bad) and would create a new Issue there. I'll be closing this issue since it's on a different project. Again, thank you!
